services:
  - type: web
    plan: free
    name: Filestorebot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/Sankar8098/pyro2      
    branch: main
   
