services:
  - type: web
    plan: free
    name: TechMagazineAutoFilterBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/itsyogieu/TechMagazineAutoFilterBot.git      
    branch: main
   
